version: 2
jobs:
  install:
    docker:
      - image: circleci/python:3.7.4
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: test
          POSTGRES_DB: example
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            pip install -r requirements/dev.txt --user
            docker container run --name flask_db_test -e POSTGRES_PASSWORD=123 -e POSTGRES_USER=circleci -p 5432:5432 -d postgres
            sleep 1
            flask db upgrade
            flask test
            docker container stop flask_db_test
            docker container rm flask_db_test
            unset DATABASE_URL
          environment:
            DATABASE_URL: postgresql://circleci:123@localhost:5432/example
            POSTGRES_DB: example
      - save_cache:
          paths: 
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
workflows:
  version: 2
  build-and-test:
    jobs:
      - install
