version: 2
jobs:
  install:
    docker:
      - image: circleci/python:3.7.6
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: example 
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt --user
            flask db upgrade
            flask test
      - save_cache:
          paths: 
            - ./flask
          key: v2-dependencies-{{ checksum "requirements.txt" }}
  doflask:
    docker:
      - image: circleci/python:3.7.6
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: example 
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            - v2-dependencies-
      - run:
          name: start flask
          command: |
          . venv/bin/activate
          flask db upgrade
          flask test
workflows:
  version: 2
  build-and-test:
    jobs:
      - install
      - doflask:
          requires:
            - install
