version: 2
jobs:
  install:
    docker:
      - image: circleci/python:3.7.6
      - image: circleci/postgres:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            pip install -r requirements/dev.txt --user
            flask db init
            flask db migrate
            flask db upgrade
      - save_cache:
          paths: 
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
workflows:
  version: 2
  build-and-test:
    jobs:
      - install
